# Generated by Django 5.2.5 on 2025-09-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='PP_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Student_Profile_pic'),
        ),
    ]
