# Generated by Django 5.2.5 on 2025-09-04 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_studentprofile_pp_name_alter_studentprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
