# Generated by Django 5.2.4 on 2025-08-02 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_student_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='SudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='student_profile')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
    ]
