# Generated by Django 5.2.4 on 2025-08-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='name',
            new_name='section',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='c_name',
        ),
        migrations.AddField(
            model_name='grade',
            name='cname',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
