# Generated by Django 5.2.6 on 2025-09-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='studentRegistration',
            new_name='studentReg',
        ),
    ]
